# Generated by Django 2.0.5 on 2018-05-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('Accuracy', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('Lidar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Input.AirborneLidar')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Input.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songTitle', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='dem',
            name='son',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Input.Son'),
        ),
    ]
